jobs:
  include:
    - language: elixir
      elixir:
        - 1.11
      otp_release:
        - 23.0
      before_script:
        - sleep 30
      script:
        - mix test --include mongo --include elastic
      services:
        - mongodb
        - elasticsearch
      cache:
        directories:
         - ./deps

    - language: node_js
      node_js:
        - 15.0
      install:
        - npm install
      script:
        - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      dist: bionic
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      cache:
        directories:
          - ./node_modules