services:
  book_bank:
    build:
      context: .
    environment:
      MIX_ENV: dev
    ports:
      - "4000:4000"
    depends_on:
      - elastic
      - mongo
  elastic:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    expose:
      - "9200"
      - "9300"
    restart: always
  mongo:
    image: mongo:latest
    expose:
      - "27017"
    restart: always