services:
  book_bank:
    build:
      context: .
    environment:
      MIX_ENV: dev
    ports:
      - "4000:4000"
    depends_on:
      - elastic
      - mongo
      - mongo-rs-initiator
      - mongo-connector
  elastic:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    command: mongod --replSet rs0 --bind_ip 0.0.0.0
  mongo-rs-initiator:
    image: mongo:latest
    command: mongo mongodb://mongo:27017 --eval 'rs.initiate();'
    depends_on:
      - mongo
  mongo-connector:
    image: yeasy/mongo-connector:latest
    depends_on:
      - elastic
      - mongo
      - mongo-rs-initiator
    environment:
      - MONGO=mongo
      - ELASTICSEARCH=elastic
